### ISSUE TITLE
提出までにやることリスト

### ISSUE THREAD

**Issue by mashharuki** [mashharuki/ETHOnline2024#29]
ETH online2024 提出までにやることを整理。

- [ ] プレゼン資料の修正とスクリプトの作成
- [x] デモの内容の整理
- [x] GaladrielコントラクトとEnvioの紐付け
- [x] Galadrielへの分析コントラクト、モンスターコントラクト、オラクルコントラクトのデプロイ
- [x] CCIPによるデモ用クロスチェーンTxスクリプトの作成
- [ ] フロントエンドの繋ぎ込み

**Comment by mashharuki** [comment]
上から2番目は、かるでねさんにお願いする。
上から4番目は、リョーマさんにお願いする。

**Comment by mashharuki** [comment]
上から1番目は、harukiが担当する。

**Comment by mashharuki** [comment]
上から6番目のフロントエンドの繋ぎ込みについては、

ユーザーが送信したTxを分析し、Galadriel上のコントラクトを呼び出してモンスターNFTを生成することができるところまでできれば今回のハッカソンではOKとする。

**Comment by mashharuki** [comment]
上から3番目の bloklessについては、優先度低め・・。
もし余力があれば・・

**Comment by mashharuki** [comment]
上から2番目についてはかるでねさんに確認してもらいました。

**Comment by mashharuki** [comment]
一番目については叩き台を作成

**Comment by yujiym** [comment]
blocklessはhostingだけだと本質的な使い方とは程遠いのでskipして良いと思います

**Comment by mashharuki** [comment]
@yujiym 了解です！

**Comment by mashharuki** [comment]
以下の項目はskip

- [ ] Blocklessへのホスティング調査
